# permissions for end users to view simpleingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simpleingress-viewer-role
rules:
- apiGroups:
  - networking.gravityloop.io
  resources:
  - simpleingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.gravityloop.io
  resources:
  - simpleingresses/status
  verbs:
  - get
